name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build . --tag arma-server-web-admin

      - name: Docker run tests
        run: docker run --env GAME_TYPE=arma3 --env GAME_PATH=/arma3 arma-server-web-admin npm test
